language: node_js
sudo: required
dist: trusty

node_js:
  - '7'

env:
  - CXX=g++-4.8

addons:
  chrome: stable
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

branches:
  only:
  - master

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
  - ng -v
  - ng lint
  - npm run test-coverage
  - ng build --target production --base-href "/vodagone/"
  - curl "http://ci.icaprojecten.nl/jenkins/job/OOSE-Vodagone-client/build?token=$JENKINS_TOKEN"
